// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpf_tracepointConnInfo struct {
	_       structs.HostLayout
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	Pid     uint32
	Tid     uint32
}

// loadBpf_tracepoint returns the embedded CollectionSpec for bpf_tracepoint.
func loadBpf_tracepoint() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Bpf_tracepointBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf_tracepoint: %w", err)
	}

	return spec, err
}

// loadBpf_tracepointObjects loads bpf_tracepoint and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpf_tracepointObjects
//	*bpf_tracepointPrograms
//	*bpf_tracepointMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpf_tracepointObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf_tracepoint()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpf_tracepointSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_tracepointSpecs struct {
	bpf_tracepointProgramSpecs
	bpf_tracepointMapSpecs
	bpf_tracepointVariableSpecs
}

// bpf_tracepointProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_tracepointProgramSpecs struct {
	KprobeTcpSendmsg      *ebpf.ProgramSpec `ebpf:"kprobe_tcp_sendmsg"`
	TraceInetSockSetState *ebpf.ProgramSpec `ebpf:"trace_inet_sock_set_state"`
}

// bpf_tracepointMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_tracepointMapSpecs struct {
	Connections *ebpf.MapSpec `ebpf:"connections"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	TempBuffer  *ebpf.MapSpec `ebpf:"temp_buffer"`
}

// bpf_tracepointVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_tracepointVariableSpecs struct {
}

// bpf_tracepointObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpf_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_tracepointObjects struct {
	bpf_tracepointPrograms
	bpf_tracepointMaps
	bpf_tracepointVariables
}

func (o *bpf_tracepointObjects) Close() error {
	return _Bpf_tracepointClose(
		&o.bpf_tracepointPrograms,
		&o.bpf_tracepointMaps,
	)
}

// bpf_tracepointMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpf_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_tracepointMaps struct {
	Connections *ebpf.Map `ebpf:"connections"`
	Events      *ebpf.Map `ebpf:"events"`
	TempBuffer  *ebpf.Map `ebpf:"temp_buffer"`
}

func (m *bpf_tracepointMaps) Close() error {
	return _Bpf_tracepointClose(
		m.Connections,
		m.Events,
		m.TempBuffer,
	)
}

// bpf_tracepointVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpf_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_tracepointVariables struct {
}

// bpf_tracepointPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpf_tracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_tracepointPrograms struct {
	KprobeTcpSendmsg      *ebpf.Program `ebpf:"kprobe_tcp_sendmsg"`
	TraceInetSockSetState *ebpf.Program `ebpf:"trace_inet_sock_set_state"`
}

func (p *bpf_tracepointPrograms) Close() error {
	return _Bpf_tracepointClose(
		p.KprobeTcpSendmsg,
		p.TraceInetSockSetState,
	)
}

func _Bpf_tracepointClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_tracepoint_x86_bpfel.o
var _Bpf_tracepointBytes []byte
