// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpf_fullConnInfo struct {
	_       structs.HostLayout
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
}

type bpf_fullDataEvent struct {
	_         structs.HostLayout
	Timestamp uint64
	Pid       uint32
	Tid       uint32
	SrcIp     uint32
	DstIp     uint32
	SrcPort   uint16
	DstPort   uint16
	DataLen   uint32
	Direction uint8
	Pad       [7]uint8
	SockPtr   uint64
	Payload   [4096]uint8
}

type bpf_fullRecvArgs struct {
	_         structs.HostLayout
	Sk        uint64
	IovBase   uint64
	IovOffset uint64
}

// loadBpf_full returns the embedded CollectionSpec for bpf_full.
func loadBpf_full() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Bpf_fullBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf_full: %w", err)
	}

	return spec, err
}

// loadBpf_fullObjects loads bpf_full and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpf_fullObjects
//	*bpf_fullPrograms
//	*bpf_fullMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpf_fullObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf_full()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpf_fullSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_fullSpecs struct {
	bpf_fullProgramSpecs
	bpf_fullMapSpecs
	bpf_fullVariableSpecs
}

// bpf_fullProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_fullProgramSpecs struct {
	KprobeTcpCleanupRbuf  *ebpf.ProgramSpec `ebpf:"kprobe_tcp_cleanup_rbuf"`
	KprobeTcpRecvmsg      *ebpf.ProgramSpec `ebpf:"kprobe_tcp_recvmsg"`
	KprobeTcpSendmsg      *ebpf.ProgramSpec `ebpf:"kprobe_tcp_sendmsg"`
	KretprobeTcpRecvmsg   *ebpf.ProgramSpec `ebpf:"kretprobe_tcp_recvmsg"`
	TraceInetSockSetState *ebpf.ProgramSpec `ebpf:"trace_inet_sock_set_state"`
}

// bpf_fullMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_fullMapSpecs struct {
	ActiveRecv            *ebpf.MapSpec `ebpf:"active_recv"`
	ConnectionFilterCache *ebpf.MapSpec `ebpf:"connection_filter_cache"`
	Connections           *ebpf.MapSpec `ebpf:"connections"`
	EventScratch          *ebpf.MapSpec `ebpf:"event_scratch"`
	Events                *ebpf.MapSpec `ebpf:"events"`
}

// bpf_fullVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_fullVariableSpecs struct {
}

// bpf_fullObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpf_fullObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_fullObjects struct {
	bpf_fullPrograms
	bpf_fullMaps
	bpf_fullVariables
}

func (o *bpf_fullObjects) Close() error {
	return _Bpf_fullClose(
		&o.bpf_fullPrograms,
		&o.bpf_fullMaps,
	)
}

// bpf_fullMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpf_fullObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_fullMaps struct {
	ActiveRecv            *ebpf.Map `ebpf:"active_recv"`
	ConnectionFilterCache *ebpf.Map `ebpf:"connection_filter_cache"`
	Connections           *ebpf.Map `ebpf:"connections"`
	EventScratch          *ebpf.Map `ebpf:"event_scratch"`
	Events                *ebpf.Map `ebpf:"events"`
}

func (m *bpf_fullMaps) Close() error {
	return _Bpf_fullClose(
		m.ActiveRecv,
		m.ConnectionFilterCache,
		m.Connections,
		m.EventScratch,
		m.Events,
	)
}

// bpf_fullVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpf_fullObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_fullVariables struct {
}

// bpf_fullPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpf_fullObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_fullPrograms struct {
	KprobeTcpCleanupRbuf  *ebpf.Program `ebpf:"kprobe_tcp_cleanup_rbuf"`
	KprobeTcpRecvmsg      *ebpf.Program `ebpf:"kprobe_tcp_recvmsg"`
	KprobeTcpSendmsg      *ebpf.Program `ebpf:"kprobe_tcp_sendmsg"`
	KretprobeTcpRecvmsg   *ebpf.Program `ebpf:"kretprobe_tcp_recvmsg"`
	TraceInetSockSetState *ebpf.Program `ebpf:"trace_inet_sock_set_state"`
}

func (p *bpf_fullPrograms) Close() error {
	return _Bpf_fullClose(
		p.KprobeTcpCleanupRbuf,
		p.KprobeTcpRecvmsg,
		p.KprobeTcpSendmsg,
		p.KretprobeTcpRecvmsg,
		p.TraceInetSockSetState,
	)
}

func _Bpf_fullClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_full_x86_bpfel.o
var _Bpf_fullBytes []byte
